apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-app.fullname" . }}
  labels:
    app: {{ include "devops-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ include "devops-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "devops-app.name" . }}
    spec:
      containers:
        - name: {{ include "devops-app.name" . }}
          image: >-
            {{- if .Values.image.digest }}
            {{ .Values.image.repository }}@{{ .Values.image.digest }}
            {{- else }}
            {{ .Values.image.repository }}:{{ .Values.image.tag }}
            {{- end }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 30
