
apiVersion: v1
kind: Service
metadata:
  name: devops-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: devops-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
