replicaCount: 3

image:
  repository: asia-south1-docker.pkg.dev/durable-rhythm-465310-i5/apps/devops-app
  tag: ""
  digest: "" 

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
