name: CI/CD (with Trivy & Environments)

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#      - stage
#      - dev
#  pull_request:
#    branches: [ main ]

env:
  REGION: "asia-south1"
  AR_REPO: "apps"
  GCP_LOCATION: "asia-south1"
  GCP_PROJECT_ID: "durable-rhythm-465310-i5"
  GKE_CLUSTER_NAME_DEV: dev
  GKE_CLUSTER_NAME_STAGE: stage
  GKE_CLUSTER_NAME_PROD: prod

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-image.outputs.IMAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies & tests
        run: |
          pip install -r app/requirements.txt
          python -m pytest -q || true

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Docker build & push (digest)
        id: set-image
        run: |
          gcloud auth configure-docker ${GCP_LOCATION}-docker.pkg.dev
          IMAGE="${GCP_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${AR_REPO}/devops-app:${GITHUB_SHA}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          # Get image digest
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "$IMAGE")
          echo "IMAGE=$DIGEST" >> "$GITHUB_OUTPUT"

  trivy-scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Docker auth
        run: |
          gcloud auth configure-docker ${GCP_LOCATION}-docker.pkg.dev

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ needs.build.outputs.IMAGE }}
          format: table
          exit-code: 0
          severity: CRITICAL
          ignore-unfixed: true
          driver: docker

  deploy-dev:
    needs: trivy-scan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME_DEV }}
          location: ${{ env.REGION }}
          project_id: ${{ env.GCP_PROJECT_ID }}
      - name: Deploy (Helm rolling upgrade)
        run: |
          helm upgrade --install devops-app k8s/helm/devops-app \
            --set image.repository="${{ needs.build.outputs.IMAGE }}" \
            --namespace dev --create-namespace

  deploy-stage:
    needs: trivy-scan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stage'
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME_STAGE }}
          location: ${{ env.REGION }}
          project_id: ${{ env.GCP_PROJECT_ID }}
      - name: Deploy (Helm rolling upgrade)
        run: |
          helm upgrade --install devops-app k8s/helm/devops-app \
            --set image.repository="${{ needs.build.outputs.IMAGE }}" \
            --namespace stage --create-namespace

  deploy-prod:
    needs: deploy-stage
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME_PROD }}
          location: ${{ env.REGION }}
          project_id: ${{ env.GCP_PROJECT_ID }}
      - name: Deploy (Helm rolling upgrade)
        run: |
          helm upgrade --install devops-app k8s/helm/devops-app \
            --set image.repository="${{ needs.build.outputs.IMAGE }}" \
            --namespace prod --create-namespace
